name: Run Python on Windows

on:
  pull_request:  # Correct event name is "pull_request"
    branches:
      - '**'  # Trigger on PRs to any branch

jobs:
  run-python-script:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Python Script
        run: python hello.py
